services:  
  php:  
    #build: .
    image: registry.cn-hangzhou.aliyuncs.com/dubux/hs-admin:latest
    container_name: hs-admin  
    network_mode: host
    restart: unless-stopped
    volumes:  
      - ./config:/etc/headscale
      - ./data:/var/lib/headscale
    environment:
      - SERVER_NET="eth0"
