#!/command/with-contenv bash

CONTAINER_DB_DIR="/var/lib/headscale"
DB_FILE="$CONTAINER_DB_DIR/db.sqlite"
if [ ! -f "$DB_FILE" ]; then
	echo "将自动生成数据库文件"
	# 初始化数据库
    cd /app
	python3 -m flask db init
	python3 -m flask db migrate
	python3 -m flask db upgrade
else
    echo "检测到SQLITE已有数据"
fi

TOKEN_FILE_PATH="${BASE_PATH}/adminui/token"
TOKEN_CONTENT=$(cat "$TOKEN_FILE_PATH" 2>/dev/null)
if [ -z "$TOKEN_CONTENT" ]; then
    BEARER_TOKEN=$("${BASE_PATH}/headscale/headscale" apikeys create)
    echo "$BEARER_TOKEN" > "$TOKEN_FILE_PATH"
else
    BEARER_TOKEN="$TOKEN_CONTENT"
fi

APP_PY_PATH="/app/config.py"
TOKEN_VALUE="$BEARER_TOKEN"
sed -i '/^BEARER_TOKEN/d' "$APP_PY_PATH"
echo "BEARER_TOKEN='$TOKEN_VALUE'" >> "$APP_PY_PATH"
python3 /app/app.py
