#!/command/with-contenv bash

TOKEN_CONTENT=$(cat "$TOKEN_FILE_PATH" 2>/dev/null)
if [ -z "$TOKEN_CONTENT" ]; then
    BEARER_TOKEN=$("${BASE_PATH}/headscale/headscale" apikeys create)
    echo "$BEARER_TOKEN"
else
    BEARER_TOKEN="$TOKEN_CONTENT"
fi
unset BEARER_TOKEN
python3 /app/app.py